# Generated by Django 5.2.4 on 2026-03-26 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria da galeria',
                'verbose_name_plural': 'Categorias da galeria',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('imagem', models.ImageField(upload_to='galeria/')),
                ('formato', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('destaque', 'Destaque')], default='horizontal', max_length=20)),
                ('alt_texto', models.CharField(blank=True, max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='core.categoriagaleria')),
            ],
            options={
                'verbose_name': 'Imagem da galeria',
                'verbose_name_plural': 'Imagens da galeria',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
