# Generated by Django 5.2.4 on 2026-03-26 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoriagaleria_imagemgaleria'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
                ('local', models.CharField(blank=True, max_length=140)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento da galeria',
                'verbose_name_plural': 'Eventos da galeria',
                'ordering': ['-data_evento', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='imagemgaleria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='core.categoriagaleria'),
        ),
        migrations.AddField(
            model_name='imagemgaleria',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imagens', to='core.eventogaleria'),
        ),
    ]
