# Generated by Django 5.2.4 on 2026-03-26 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventogaleria_alter_imagemgaleria_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventogaleria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='core.categoriagaleria'),
        ),
    ]
