# Generated by Django 5.2.4 on 2026-03-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventogaleria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemgaleria',
            name='destaque_home',
            field=models.BooleanField(default=False),
        ),
    ]
