# Generated by Django 5.2.12 on 2026-03-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imagemgaleria_destaque_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Rosa Chá Catering', max_length=120)),
                ('telefone_whatsapp', models.CharField(default='+351 932 079 149', max_length=30)),
                ('email_contato', models.EmailField(default='contato@rosachacatering.pt', max_length=254)),
                ('instagram_url', models.URLField(default='https://instagram.com')),
                ('instagram_usuario', models.CharField(default='@rosacha', max_length=80)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informações da empresa',
                'verbose_name_plural': 'Informações da empresa',
            },
        ),
    ]
