# Generated by Django 5.2.12 on 2026-03-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_informacoesempresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoesempresa',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='facebook_usuario',
            field=models.CharField(blank=True, default='@rosacha', max_length=80),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='tiktok_url',
            field=models.URLField(blank=True, default='https://tiktok.com'),
        ),
        migrations.AddField(
            model_name='informacoesempresa',
            name='tiktok_usuario',
            field=models.CharField(blank=True, default='@rosacha', max_length=80),
        ),
    ]
